# Install this environment with:
# conda env create -f environment.yml
#
# If you make changes to this file, update the environment with:
# conda env update -f environment.yml

name: mtec-345
channels:
  # - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytorch::pytorch=2.4
  - numpy
  - jupyter
  - scipy
  - matplotlib
  - pip:
    - librosa

